package org.example.selenium.webdriver.pageobjectpattern;

// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.example.selenium.webdriver.pageobjectpattern.module.MainMenuPageObjectModel;
import org.junit.Rule;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.testcontainers.containers.BrowserWebDriverContainer;

import java.util.HashMap;
import java.util.Map;

public class PageObjectPatternTestScenario {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @BeforeAll
    public static void beforeAll() {
        WebDriverManager.chromedriver().setup();
    }

    @BeforeEach
    public void beforeEach(){
//        driver = new ChromeDriver();
        BrowserWebDriverContainer<?> chrome = new BrowserWebDriverContainer<>().withCapabilities(new ChromeOptions());
        RemoteWebDriver driver = new RemoteWebDriver(chrome.getSeleniumAddress(), new ChromeOptions());
        js = (JavascriptExecutor) driver;
        vars = new HashMap<>();
    }

    @AfterEach
    public void afterEach() {
        driver.quit();
    }

    @Test
    public void fIRSTTEST() {
        driver.get("http://gastro-tech.net/");
        driver.manage().window().setSize(new Dimension(1436, 864));

        MainMenuPageObjectModel.clickHome(driver);
        MainMenuPageObjectModel.clickOFirmie(driver);
        MainMenuPageObjectModel.clickOferta(driver);
        MainMenuPageObjectModel.clickSerwis(driver);

        System.out.println();
    }
}

