package org.example.selenium.webdriver.basic;

// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.pagefactory.ByChained;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class FirstWebdriverTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @BeforeAll
  public static void beforeAll() {
    WebDriverManager.chromedriver().setup();
  }

  @BeforeEach
  public void beforeEach(){
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<>();
  }

  @AfterEach
  public void afterEach() {
    driver.quit();
  }

  @Test
  public void fIRSTTEST() {
    driver.get("http://gastro-tech.net/");
    driver.manage().window().setSize(new Dimension(1436, 864));

    By topMainMenuSelector = By.cssSelector("#menu-menu-glowne");
    By oFirmieSelector = By.cssSelector("li:nth-child(2)");
    By ofertaSelector = By.cssSelector("li:nth-child(3)");
    By serwisSelector = By.cssSelector("li:nth-child(4)");

    driver.findElement(new ByChained(topMainMenuSelector, oFirmieSelector)).click();
    driver.findElement(new ByChained(topMainMenuSelector, ofertaSelector)).click();
    driver.findElement(new ByChained(topMainMenuSelector, serwisSelector)).click();

    System.out.println();
  }
}
